buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath libs.junit.platform.gradle.plugin
    }
}

apply plugin: 'org.junit.platform.gradle.plugin'

junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://dl.bintray.com/jetbrains/spek" }
}

dependencies {
    implementation project(":mirakle")
    testImplementation gradleTestKit()
    testImplementation libs.kotlin.stdlib
    testImplementation libs.kotlin.reflect
    testImplementation libs.kotlin.test
    testImplementation libs.spek.api
    testImplementation libs.junit.platform.launcher
    testImplementation libs.spek.junit.platform.engine
}
